server:
  servlet:
    session:
      timeout: 120
  port: 8082

spring:
  application:
    name: "product-craftsman-service"
  profiles:
    active: "default"
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
