server:
  port: 8083

spring:
  application:
    name: "cart-expresso-service"
  profiles:
    active: "default"
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672

management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
resilience4j.retry:
  configs:
    default:
      maxRetryAttempts: 3
      waitDuration: 300
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
feign:
  client:
    config:
      default:
        loggerLevel: FULL

razorpay-config:
  keyId: ${RAZORPAY_ID}
  keySecret: ${RAZORPAY_SECRET}
service-config:
  externalServiceException:
    code: 7000
    description: External Service Exception
  internalServerException:
    code: 5000
    description: Internal Server Exception
  businessException:
    code: 6000
    description: Business validation Exception
  externalServiceExceptions:
    productCraftsmanService:
      code: 700001
      description: Error from the Products Craftsman Service



